import argparse
import json
import os

import cv2
import mmcv
import numpy as np
from pyquaternion import Quaternion

NUSC_TO_RAW_CAM = {
    'CAM_FRONT': 'front',
    'CAM_FRONT_LEFT': 'front_left',
    'CAM_FRONT_RIGHT': 'front_right',
    'CAM_BACK': 'rear',
    'CAM_BACK_LEFT': 'rear_left',
    'CAM_BACK_RIGHT': 'rear_right',
}

BOX_EDGES = [
    (0, 1),
    (1, 2),
    (2, 3),
    (3, 0),
    (4, 5),
    (5, 6),
    (6, 7),
    (7, 4),
    (0, 4),
    (1, 5),
    (2, 6),
    (3, 7),
]


def parse_args():
    parser = argparse.ArgumentParser(
        description='Visualize Town01 annotations from generated infos pkl.')
    parser.add_argument('--infos',
                        type=str,
                        default='./data/town01_pickle/town01_infos_train.pkl',
                        help=('Path to town01 infos pkl (defaults to the valid '
                              'train pickle generated by gen_info_carla.py).'))
    parser.add_argument('--sequence-root',
                        type=str,
                        default='./Town01/seq_0001',
                        help='Root folder of Town01 sequence.')
    parser.add_argument('--output-dir',
                        type=str,
                        default='./outputs/town01_vis',
                        help='Directory to store rendered images.')
    parser.add_argument('--start-index',
                        type=int,
                        default=0,
                        help='Start sample index in infos list.')
    parser.add_argument('--max-samples',
                        type=int,
                        default=10,
                        help='Number of samples to visualize.')
    parser.add_argument('--draw-source-2d',
                        action='store_true',
                        help='Draw projected 2D boxes from boxes_3d frame json in red.')
    parser.add_argument('--visibility-filter',
                        type=str,
                        default='none',
                        choices=['none', 'frustum', 'depth', 'frustum-depth'],
                        help=('Visibility filter for 3D boxes: '
                              'none=draw all, frustum=use frame json camera_observations, '
                              'depth=use depth map occlusion test, '
                              'frustum-depth=apply both.'))
    parser.add_argument('--depth-margin-m',
                        type=float,
                        default=1.0,
                        help='Allowed margin in meters when comparing projected box depth and depth map.')
    return parser.parse_args()


def quaternion_to_rot(q):
    return Quaternion(q).rotation_matrix.astype(np.float32)


def world_to_camera(points_world, cam_info):
    ego_pose = cam_info['ego_pose']
    calib = cam_info['calibrated_sensor']

    r_ego_global = quaternion_to_rot(ego_pose['rotation'])
    t_ego_global = np.array(ego_pose['translation'], dtype=np.float32)

    r_cam_ego = quaternion_to_rot(calib['rotation'])
    t_cam_ego = np.array(calib['translation'], dtype=np.float32)

    points_ego = (r_ego_global.T @ (points_world - t_ego_global).T).T
    points_cam_raw = (r_cam_ego.T @ (points_ego - t_cam_ego).T).T

    # Town01 frame JSON uses the camera convention [x, y, z] = [right, up, forward]
    # for bbox_center_camera_xyz_m, while the raw transform above yields the
    # intermediate CARLA-like camera frame. Reorder to the JSON convention so
    # projection matches the dataset annotations.
    points_cam = np.stack(
        [points_cam_raw[:, 1], -points_cam_raw[:, 2], points_cam_raw[:, 0]],
        axis=1,
    )
    return points_cam


def project_points(points_cam, cam_intrinsic):
    k = np.array(cam_intrinsic, dtype=np.float32)
    z = points_cam[:, 2:3]
    z_safe = np.where(z == 0, 1e-6, z)
    uvw = (k @ points_cam.T).T
    uv = uvw[:, :2] / z_safe
    valid = (z[:, 0] > 1e-3)
    return uv, valid


def box_corners_world(translation, size, rotation):
    center = np.array(translation, dtype=np.float32)
    sx, sy, sz = [float(v) for v in size]

    # Keep convention aligned with ann size used by dataset generation.
    dx = sx
    dy = sy
    dz = sz

    x = dx / 2.0
    y = dy / 2.0
    z = dz / 2.0

    corners_local = np.array([
        [x, y, -z],
        [x, -y, -z],
        [-x, -y, -z],
        [-x, y, -z],
        [x, y, z],
        [x, -y, z],
        [-x, -y, z],
        [-x, y, z],
    ], dtype=np.float32)

    r_box_world = quaternion_to_rot(rotation)
    corners_world = (r_box_world @ corners_local.T).T + center
    return corners_world


def parse_track_id(instance_token):
    if instance_token is None:
        return None
    s = str(instance_token)
    # Expected format from generator: "track_<id>"
    if s.startswith('track_'):
        tail = s.split('track_', 1)[1]
        if tail.isdigit():
            return int(tail)
    # Fallback: extract last integer chunk.
    chunks = ''.join([c if c.isdigit() else ' ' for c in s]).split()
    if len(chunks) == 0:
        return None
    return int(chunks[-1])


def build_track_observation_map(frame_json, raw_cam_name):
    obs_map = {}
    if frame_json is None:
        return obs_map
    for inst in frame_json.get('instances', []):
        track_id = inst.get('track_id', None)
        if track_id is None:
            continue
        obs = inst.get('camera_observations', {}).get(raw_cam_name, {})
        obs_map[int(track_id)] = obs
    return obs_map


def load_depth_map(sequence_root, cam_info):
    depth_rel = cam_info.get('depth_filename', None)
    if not depth_rel:
        return None
    depth_path = os.path.join(sequence_root, depth_rel)
    if not os.path.exists(depth_path):
        return None
    data = np.load(depth_path)
    if 'depth' in data.files:
        return data['depth'].astype(np.float32)
    if len(data.files) > 0:
        return data[data.files[0]].astype(np.float32)
    return None


def center_depth_visible(center_world, cam_info, depth_map, margin_m):
    if depth_map is None:
        return True
    center_world = np.array(center_world, dtype=np.float32).reshape(1, 3)
    center_cam = world_to_camera(center_world, cam_info)
    center_uv, valid = project_points(
        center_cam, cam_info['calibrated_sensor']['camera_intrinsic'])
    if not valid[0]:
        return False

    u = int(round(float(center_uv[0, 0])))
    v = int(round(float(center_uv[0, 1])))
    h, w = depth_map.shape[:2]
    if u < 0 or u >= w or v < 0 or v >= h:
        return False

    predicted_depth = float(center_cam[0, 2])
    depth_sensor = float(depth_map[v, u])
    # 1000.0 is used as far/no-hit in this dataset.
    if depth_sensor >= 999.0:
        return True
    return predicted_depth <= depth_sensor + margin_m


def draw_3d_boxes_from_ann_infos(image,
                                 cam_info,
                                 ann_infos,
                                 raw_cam_name=None,
                                 frame_json=None,
                                 depth_map=None,
                                 visibility_filter='none',
                                 depth_margin_m=1.0,
                                 color=(0, 255, 0)):
    obs_map = {}
    if visibility_filter in ('frustum', 'frustum-depth'):
        obs_map = build_track_observation_map(frame_json, raw_cam_name)

    for ann in ann_infos:
        if visibility_filter in ('frustum', 'frustum-depth'):
            track_id = parse_track_id(ann.get('instance_token'))
            obs = obs_map.get(track_id, None)
            if obs is None or not obs.get('is_in_frustum', False):
                continue

        if visibility_filter in ('depth', 'frustum-depth'):
            if not center_depth_visible(ann['translation'], cam_info, depth_map,
                                        depth_margin_m):
                continue

        corners_world = box_corners_world(ann['translation'], ann['size'],
                                          ann['rotation'])
        corners_cam = world_to_camera(corners_world, cam_info)
        corners_uv, valid = project_points(
            corners_cam, cam_info['calibrated_sensor']['camera_intrinsic'])

        for st, ed in BOX_EDGES:
            if not (valid[st] and valid[ed]):
                continue
            pt1 = tuple(corners_uv[st].astype(np.int32))
            pt2 = tuple(corners_uv[ed].astype(np.int32))
            cv2.line(image, pt1, pt2, color, 2)
    return image


def draw_source_2d_boxes(image, frame_json, raw_cam_name, color=(0, 0, 255)):
    for inst in frame_json.get('instances', []):
        obs = inst.get('camera_observations', {}).get(raw_cam_name, {})
        if not obs.get('is_in_frustum', False):
            continue
        bbox = obs.get('projected_bbox_xyxy', None)
        if bbox is None:
            continue
        x1, y1, x2, y2 = [int(v) for v in bbox]
        cv2.rectangle(image, (x1, y1), (x2, y2), color, 2)
    return image


def sample_token_to_frame_id(sample_token):
    # Format expected: seq_0001_0000002493
    return int(sample_token.split('_')[-1])


def main():
    args = parse_args()
    infos = mmcv.load(args.infos)
    os.makedirs(args.output_dir, exist_ok=True)

    start = max(args.start_index, 0)
    end = min(start + args.max_samples, len(infos))

    for idx in range(start, end):
        info = infos[idx]
        sample_token = info['sample_token']
        frame_id = sample_token_to_frame_id(sample_token)

        frame_json = None
        need_frame_json = args.draw_source_2d or args.visibility_filter in (
            'frustum', 'frustum-depth')
        if need_frame_json:
            frame_json_path = os.path.join(args.sequence_root, 'boxes_3d', 'frames',
                                           f'{frame_id:010d}.json')
            if os.path.exists(frame_json_path):
                with open(frame_json_path, 'r') as f:
                    frame_json = json.load(f)

        for nus_cam_name, cam_info in info['cam_infos'].items():
            img_path = os.path.join(args.sequence_root, cam_info['filename'])
            if not os.path.exists(img_path):
                continue
            image = cv2.imread(img_path)
            if image is None:
                continue

            raw_cam_name = NUSC_TO_RAW_CAM.get(nus_cam_name, None)
            depth_map = None
            if args.visibility_filter in ('depth', 'frustum-depth'):
                depth_map = load_depth_map(args.sequence_root, cam_info)

            image = draw_3d_boxes_from_ann_infos(
                image,
                cam_info,
                info['ann_infos'],
                raw_cam_name=raw_cam_name,
                frame_json=frame_json,
                depth_map=depth_map,
                visibility_filter=args.visibility_filter,
                depth_margin_m=args.depth_margin_m,
            )

            if frame_json is not None and nus_cam_name in NUSC_TO_RAW_CAM:
                image = draw_source_2d_boxes(image, frame_json, raw_cam_name)

            out_name = f'{sample_token}_{nus_cam_name}.png'
            out_path = os.path.join(args.output_dir, out_name)
            cv2.imwrite(out_path, image)

    print(f'Visualization done for samples [{start}, {end}) at: {args.output_dir}')


if __name__ == '__main__':
    main()
